version: '3.8'

services:
  ilmac-ubuntu-dev:
    build: .
    container_name: ilmac-ubuntu-dev
    restart: unless-stopped
    ports:
      # SSH
      - "${SV_PORT_SSH}:${SV_PORT_SSH}"
      # Frontend
      ##  bid-notice-web
      - "${FE_PORT_BID_NOTICE_NEXTJS}:${FE_PORT_BID_NOTICE_NEXTJS}"  # bid-notice-web:nextjs
      # Backend servers
      ##  bid-notice-web
      - "${BE_PORT_BID_NOTICE_SPIDER}:${BE_PORT_BID_NOTICE_SPIDER}"  # bid-notice-web:spider server
      - "${BE_PORT_BID_NOTICE_MYSQL}:${BE_PORT_BID_NOTICE_MYSQL}"  # bid-notice-web:mysql server
      - "${BE_PORT_BID_NOTICE_BID}:${BE_PORT_BID_NOTICE_BID}"  # bid-notice-web:bid server
      - "${BE_PORT_BID_NOTICE_BOARD}:${BE_PORT_BID_NOTICE_BOARD}"  # bid-notice-web:board server
    volumes:
      # NAS 전체 볼륨을 /nas에 마운트
      - /volume1:/nas
      # 현재 디렉토리를 /_exp에 마운트
      - ./:/_exp
    stdin_open: true
    tty: true
    environment:
      # github 설정(jna-cli)
      - ENV_GITHUB_OWNER=${ENV_GITHUB_OWNER}
      - ENV_GITHUB_REPO=${ENV_GITHUB_REPO}
      - ENV_GITHUB_TOKEN=${ENV_GITHUB_TOKEN}

      # MySQL 설정
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_BID_DATABASE=${MYSQL_BID_DATABASE}
    # SSH 및 cron 서비스 시작 후 컨테이너 유지
    command: >
      /bin/sh -c "service ssh start && 
                  service cron start && 
                  /_exp/projects/bid-notice-web_entrypoint.sh &
                  tail -f /dev/null"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge