version: '3.8'

services:
  ilmac-ubuntu-dev:
    build: .
    container_name: ilmac-ubuntu-dev
    restart: unless-stopped
    ports:
      # SSH
      - "${SV_SSH_PORT}:${SV_SSH_PORT}"
      # Frontend
      ##  bid-notice-web
      - "${FE_PORT_BID_NOTICE_NEXTJS}:${FE_PORT_BID_NOTICE_NEXTJS}"  # bid-notice-web:nextjs
      # Backend servers
      ##  bid-notice-web
      - "${BE_PORT_BID_NOTICE_SPIDER}:${BE_PORT_BID_NOTICE_SPIDER}"  # bid-notice-web:spider server
      - "${BE_PORT_BID_NOTICE_MYSQL}:${BE_PORT_BID_NOTICE_MYSQL}"  # bid-notice-web:mysql server
      - "${BE_PORT_BID_NOTICE_BID}:${BE_PORT_BID_NOTICE_BID}"  # bid-notice-web:bid server
      - "${BE_PORT_BID_NOTICE_BOARD}:${BE_PORT_BID_NOTICE_BOARD}"  # bid-notice-web:board server
    volumes:
      # NAS 전체 볼륨을 /nas에 마운트
      - /volume1:/nas
      # 현재 디렉토리를 /_exp에 마운트
      - ./:/_exp
      # VSCode 및 Cursor 확장 프로그램 지속성을 위한 볼륨
      - ./ide/.cursor-server:/root/.cursor-server
      - ./ide/.vscode-server:/root/.vscode-server
      # bashrc 설정 파일 마운트
      - ./configs/.bashrc:/root/.bashrc
      - ./configs/crontab:/etc/cron.d/app-crontab
      # - "${NAS_CURSOR_SERVER_PATH}:/root/.cursor-server"
      # - "${NAS_VSCODE_SERVER_PATH}:/root/.vscode-server"

    stdin_open: true
    tty: true
    environment:
      # SSH 설정
      - SSH_PORT=${SV_SSH_PORT}
      - ROOT_PASSWORD=${SV_SSH_ROOT_PASSWORD}

      # github 설정(jna-cli)
      - ENV_GITHUB_OWNER=${ENV_GITHUB_OWNER}
      - ENV_GITHUB_REPO=${ENV_GITHUB_REPO}
      - ENV_GITHUB_TOKEN=${ENV_GITHUB_TOKEN}

      # MySQL 설정
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_BID_DATABASE=${MYSQL_BID_DATABASE}
    # 서비스 시작 후 컨테이너 유지
    command: >
      /bin/sh -c "
        /_exp/docker-start.sh &&
        /_exp/projects/bid-notice-web_entrypoint.sh &
        tail -f /dev/null"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge